// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqupbfrcootryorjoicz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxdXBiZnJjb290cnlvcmpvaWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Nzk2MTAsImV4cCI6MjA2NTA1NTYxMH0.DhNMghJrvp6lawj6JA602ZmxI_ktjLfcgVz52sZk9as";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);